Tasks: homework5::DocumentModel Class Reference
homework5::DocumentModel Class Reference
#include </home/travis/build/gvenewour/miscellaneous/homeworks/homework5/include/model.h>
Public Member Functions
int importFromFile (const fs::path &path)
int exportToFile (const fs::path &path)
template<typename T , typename... Args>
int addPrimitive (Args &&...args)
const Primitives & getPrimitives () const
int removeLastAdded ()
int removeAll ()
Protected Attributes
Primitives _primitives
Detailed Description
Definition at line 17 of file model.h.
Member Function Documentation
template<typename T , typename... Args> int homework5::DocumentModel::addPrimitive (Args &&... args) inline
Definition at line 23 of file model.h.
References _primitives, and homework5::OK.
Referenced by homework5::Controller::addLine(), homework5::Controller::addPoint(), and TEST().
int homework5::DocumentModel::exportToFile (const fs::path & path)
Definition at line 9 of file model.cpp.
References homework5::OK.
Referenced by homework5::Controller::exportDoc(), and TEST().
const Primitives& homework5::DocumentModel::getPrimitives () const inline
Definition at line 29 of file model.h.
References _primitives.
Referenced by homework5::ViewCLI::_showDocState(), and TEST().
int homework5::DocumentModel::importFromFile (const fs::path & path)
Definition at line 4 of file model.cpp.
References homework5::OK.
Referenced by homework5::Controller::importDoc(), and TEST().
int homework5::DocumentModel::removeAll ()
Definition at line 21 of file model.cpp.
References _primitives, and homework5::OK.
Referenced by homework5::Controller::createDoc(), and TEST().
int homework5::DocumentModel::removeLastAdded ()
Definition at line 14 of file model.cpp.
References _primitives, and homework5::OK.
Referenced by homework5::Controller::removeLastAdded(), and TEST().
Member Data Documentation
Primitives homework5::DocumentModel::_primitives protected
Definition at line 37 of file model.h.
Referenced by addPrimitive(), getPrimitives(), removeAll(), and removeLastAdded().
The documentation for this class was generated from the following files:
/home/travis/build/gvenewour/miscellaneous/homeworks/homework5/include/model.h
/home/travis/build/gvenewour/miscellaneous/homeworks/homework5/src/model.cpp