Tasks: homework5::ViewCLI Class Reference
homework5::ViewCLI Class Reference
#include </home/travis/build/gvenewour/miscellaneous/homeworks/homework5/include/view_cli.h>
Public Member Functions
ViewCLI ()
ViewCLI (const ViewCLI &)=delete
ViewCLI & operator= (const ViewCLI &)=delete
ViewCLI (ViewCLI &&)=delete
ViewCLI & operator= (ViewCLI &&)=delete
~ViewCLI () override=default
int start (DocumentModel *model, Controller *controler) override
Public Member Functions inherited from homework5::View
virtual ~View ()=default
Protected Member Functions
int _init (DocumentModel *model, Controller *controller)
int _showDocState ()
bool _isOpAvailable (Operation operation)
Protected Attributes
bool _primitivesAvailable
Controller * _controller
DocumentModel * _model
std::map< Operation, std::pair
< std::string, std::function
< int()> > > _dispatcher
Detailed Description
Definition at line 14 of file view_cli.h.
Constructor & Destructor Documentation
homework5::ViewCLI::ViewCLI () inline
Definition at line 16 of file view_cli.h.
homework5::ViewCLI::ViewCLI (const ViewCLI &) delete
homework5::ViewCLI::ViewCLI (ViewCLI &&) delete
homework5::ViewCLI::~ViewCLI () override default
Member Function Documentation
int homework5::ViewCLI::_init (DocumentModel * model, Controller * controller) protected
Definition at line 77 of file view_cli.cpp.
References _controller, _dispatcher, _model, homework5::addLine, homework5::Controller::addLine(), homework5::addPoint, homework5::Controller::addPoint(), homework5::create, homework5::Controller::createDoc(), homework5::Controller::exportDoc(), homework5::exportFrom, homework5::import, homework5::Controller::importDoc(), homework5::NOT_INITIALIZED, homework5::removeLastAdded, and homework5::Controller::removeLastAdded().
Referenced by start().
bool homework5::ViewCLI::_isOpAvailable (homework5::Operation operation) protected
Definition at line 73 of file view_cli.cpp.
References _primitivesAvailable, and homework5::removeLastAdded.
Referenced by start().
int homework5::ViewCLI::_showDocState () protected
Definition at line 97 of file view_cli.cpp.
References _controller, _model, _primitivesAvailable, homework5::DocumentModel::getPrimitives(), homework5::NOT_INITIALIZED, and homework5::OK.
Referenced by start().
ViewCLI& homework5::ViewCLI::operator= (const ViewCLI &) delete
ViewCLI& homework5::ViewCLI::operator= (ViewCLI &&) delete
int homework5::ViewCLI::start (DocumentModel * model, Controller * controler) override virtual
Implements homework5::View.
Definition at line 20 of file view_cli.cpp.
References _dispatcher, _init(), _isOpAvailable(), _showDocState(), homework5::INVALID_REQUEST, homework5::maxOp, homework5::NOT_INITIALIZED, and homework5::OK.
Referenced by homework5::Controller::startUI(), and TEST().
Member Data Documentation
Controller* homework5::ViewCLI::_controller protected
Definition at line 36 of file view_cli.h.
Referenced by _init(), and _showDocState().
std::map<Operation, std::pair<std::string, std::function<int()> > > homework5::ViewCLI::_dispatcher protected
Definition at line 39 of file view_cli.h.
Referenced by _init(), and start().
DocumentModel* homework5::ViewCLI::_model protected
Definition at line 37 of file view_cli.h.
Referenced by _init(), and _showDocState().
bool homework5::ViewCLI::_primitivesAvailable protected
Definition at line 34 of file view_cli.h.
Referenced by _isOpAvailable(), and _showDocState().
The documentation for this class was generated from the following files:
/home/travis/build/gvenewour/miscellaneous/homeworks/homework5/include/view_cli.h
/home/travis/build/gvenewour/miscellaneous/homeworks/homework5/src/view_cli.cpp