Tasks: homework5::Controller Class Reference
homework5::Controller Class Reference
#include </home/travis/build/gvenewour/miscellaneous/homeworks/homework5/include/controller.h>
Public Member Functions
Controller ()=default
Controller (const Controller &)=delete
Controller & operator= (const Controller &)=delete
Controller (Controller &&)=delete
Controller & operator= (Controller &&)=delete
~Controller ()=default
int startUI ()
int createDoc ()
int importDoc ()
int importDoc (const std::string &name)
int exportDoc ()
int exportDoc (const std::string &name)
int addLine ()
int addLine (Point start, Point end)
int addLine (Coordinate x1, Coordinate y1, Coordinate x2, Coordinate y2)
int addPoint ()
int removeLastAdded ()
Detailed Description
Definition at line 8 of file controller.h.
Constructor & Destructor Documentation
homework5::Controller::Controller () default
homework5::Controller::Controller (const Controller &) delete
homework5::Controller::Controller (Controller &&) delete
homework5::Controller::~Controller () default
Member Function Documentation
int homework5::Controller::addLine ()
Definition at line 36 of file controller.cpp.
Referenced by homework5::ViewCLI::_init(), and TEST().
int homework5::Controller::addLine (Point start, Point end)
Definition at line 41 of file controller.cpp.
References homework5::DocumentModel::addPrimitive().
int homework5::Controller::addLine (Coordinate x1, Coordinate y1, Coordinate x2, Coordinate y2)
Definition at line 45 of file controller.cpp.
References homework5::DocumentModel::addPrimitive().
int homework5::Controller::addPoint ()
Definition at line 49 of file controller.cpp.
References homework5::DocumentModel::addPrimitive().
Referenced by homework5::ViewCLI::_init(), and TEST().
int homework5::Controller::createDoc ()
Definition at line 16 of file controller.cpp.
References homework5::DocumentModel::removeAll().
Referenced by homework5::ViewCLI::_init(), and TEST().
int homework5::Controller::exportDoc ()
Definition at line 28 of file controller.cpp.
Referenced by homework5::ViewCLI::_init(), and TEST().
int homework5::Controller::exportDoc (const std::string & name)
Definition at line 32 of file controller.cpp.
References homework5::DocumentModel::exportToFile().
int homework5::Controller::importDoc ()
Definition at line 20 of file controller.cpp.
Referenced by homework5::ViewCLI::_init(), and TEST().
int homework5::Controller::importDoc (const std::string & name)
Definition at line 24 of file controller.cpp.
References homework5::DocumentModel::importFromFile().
Controller& homework5::Controller::operator= (const Controller &) delete
Controller& homework5::Controller::operator= (Controller &&) delete
int homework5::Controller::removeLastAdded ()
Definition at line 54 of file controller.cpp.
References homework5::DocumentModel::removeLastAdded().
Referenced by homework5::ViewCLI::_init(), and TEST().
int homework5::Controller::startUI ()
Definition at line 12 of file controller.cpp.
References homework5::ViewCLI::start().
Referenced by main().
The documentation for this class was generated from the following files:
/home/travis/build/gvenewour/miscellaneous/homeworks/homework5/include/controller.h
/home/travis/build/gvenewour/miscellaneous/homeworks/homework5/src/controller.cpp