Tasks: homework3 Namespace Reference
homework3 Namespace Reference
ДЗ-3 (allocator). Задание на реализацию кастомного аллокатора и контейнеров
Namespaces
impl
Внутренние детали реализации контейнера homework3::CustomList.
shm
Внутренние детали работы с аллокаторами boost::interprocess.
Classes
class SimpleFixedArena
Класс, представляющий арену фиксированного размера
class CustomList
Кастомная реализация однонаправленного списка. Поддерживает работу с homework3::LinearStatefulAllocator.
class LinearStatefulAllocator
Кастомный аллокатор. Поддерживает нодовые контейнеры
class MemoryResource
Основа для работы с любым memory resource.
Typedefs
using Key = int
Тип ключа в нодовых контейнерах ДЗ-3.
using Val = int
Тип значения в нодовых контейнерах ДЗ-3.
using CustomMap = std::map< Key, Val, std::less<>, homework3::LinearStatefulAllocator< std::pair< const Key, Val >, maxCount > >
Functions
constexpr int factorial (int n)
Тривиальная функция вычисления факториала
template<typename T >
void fill (T &map)
Заполняет контейнер map ключами от 0 до homework3::maxCount и значениями homework3::factorial()
template<typename T >
std::string toKeyValString (T &map)
Формирует строку из элементов контейнера map в формате [ключ значение].
void exampleFastPoolAllocator ()
void exampleCustomList ()
void exampleShmAllocator ()
void examplesCustomAllocator ()
void exampleDefault ()
void exampleCopyCtor ()
void exampleMoveCtor ()
void exampleCopyAssignment ()
void exampleMoveAssignment ()
Variables
constexpr uint_least8_t MaxVerbosity = 9
Уровень выставляется при использовании параметра командной строки –verbose.
constexpr uint_least8_t maxCount {10}
Верхняя граница количества элементов в контейнерах ДЗ-3.
Typedef Documentation
using homework3::CustomMap = typedef std::map<Key, Val, std::less<>, homework3::LinearStatefulAllocator<std::pair<const Key, Val>, maxCount> >
Definition at line 12 of file examples_custom_allocator.cpp.
using homework3::Key = typedef int
Definition at line 22 of file common.h.
using homework3::Val = typedef int
Definition at line 27 of file common.h.
Function Documentation
void homework3::exampleCopyAssignment ()
Definition at line 98 of file examples_custom_allocator.cpp.
Referenced by examplesCustomAllocator().
void homework3::exampleCopyCtor ()
Definition at line 43 of file examples_custom_allocator.cpp.
Referenced by examplesCustomAllocator().
void homework3::exampleCustomList ()
Definition at line 14 of file example_custom_list.cpp.
References homework3::CustomList< T, A >::insert(), and maxCount.
Referenced by main().
void homework3::exampleDefault ()
Definition at line 37 of file examples_custom_allocator.cpp.
Referenced by examplesCustomAllocator().
void homework3::exampleFastPoolAllocator ()
Definition at line 11 of file example_boost_pool.cpp.
References maxCount.
Referenced by main().
void homework3::exampleMoveAssignment ()
Definition at line 119 of file examples_custom_allocator.cpp.
Referenced by examplesCustomAllocator().
void homework3::exampleMoveCtor ()
Definition at line 59 of file examples_custom_allocator.cpp.
Referenced by examplesCustomAllocator().
void homework3::examplesCustomAllocator ()
Definition at line 14 of file examples_custom_allocator.cpp.
References exampleCopyAssignment(), exampleCopyCtor(), exampleDefault(), exampleMoveAssignment(), and exampleMoveCtor().
Referenced by main().
void homework3::exampleShmAllocator ()
Definition at line 30 of file example_interprocess_allocators.cpp.
Referenced by main().
constexpr int homework3::factorial (int n)
Definition at line 38 of file common.h.
Referenced by fill(), and TEST().
template<typename T > void homework3::fill (T & map)
Definition at line 46 of file common.h.
References factorial(), and maxCount.
template<typename T > std::string homework3::toKeyValString (T & map)
Definition at line 56 of file common.h.
Variable Documentation
constexpr uint_least8_t homework3::maxCount {10}
Definition at line 32 of file common.h.
Referenced by homework3::LinearStatefulAllocator< T, maxCount >::allocate(), exampleCustomList(), exampleFastPoolAllocator(), fill(), and TEST().
constexpr uint_least8_t homework3::MaxVerbosity = 9
Definition at line 17 of file common.h.
Referenced by homework3::LinearStatefulAllocator< T, maxCount >::allocate(), homework3::LinearStatefulAllocator< T, maxCount >::construct(), homework3::SimpleFixedArena::deallocate(), homework3::LinearStatefulAllocator< T, maxCount >::deallocate(), homework3::LinearStatefulAllocator< T, maxCount >::destroy(), and homework3::LinearStatefulAllocator< T, maxCount >::select_on_container_copy_construction().