Tasks: homework4 Namespace Reference
homework4 Namespace Reference
ДЗ-4 (print_ip). Задание на перегрузку функций вывода ip адреса
Namespaces
impl
Внутренние детали реализации печати адресов
Functions
template<typename T >
std::enable_if_t
< std::is_integral< typename
std::decay< T >::type >::value,
std::string > print_ip (T &&address)
Печать адреса на основе числовых типов
template<typename T >
std::enable_if_t
< std::is_convertible
< typename std::decay< T >
::type, std::string >::value,
std::string > print_ip (T &&address)
Печать адреса на основе std::string.
template<typename T >
std::enable_if_t
< impl::is_allowed_container
< T >::value, std::string > print_ip (T &&address)
Печать адреса на основе контейнеров std::vector и std::list.
template<typename T >
std::enable_if_t
< impl::allowed_tuple_types< T,
std::tuple_size< T >::value >
::value, std::string > print_ip (T address)
Печать адреса на основе кортежей
Function Documentation
template<typename T > std::enable_if_t<std::is_integral<typename std::decay<T>::type>::value, std::string> homework4::print_ip (T && address)
Definition at line 43 of file base_cases.h.
References homework4::impl::printBytes().
Referenced by main(), and TEST().
template<typename T > std::enable_if_t<std::is_convertible<typename std::decay<T>::type, std::string>::value, std::string> homework4::print_ip (T && address)
Definition at line 52 of file base_cases.h.
template<typename T > std::enable_if_t<impl::allowed_tuple_types<T, std::tuple_size<T>::value>::value, std::string> homework4::print_ip (T address)
Definition at line 56 of file tuple_cases.h.
References homework4::impl::print().
template<typename T > std::enable_if_t<impl::is_allowed_container<T>::value, std::string> homework4::print_ip (T && address)
Definition at line 61 of file base_cases.h.
References homework4::impl::printBytes().