Tasks: /home/travis/build/gvenewour/miscellaneous/homeworks/homework5/test/test_homework5.cpp File Reference
test_homework5.cpp File Reference
#include "gtest/gtest.h"
#include <string>
#include "controller.h"
Functions
TEST (Homework5, ModelDefault)
TEST (Homework5, ModelDataManipulation)
TEST (Homework5, ModelFileStub)
TEST (Homework5, ViewDefault)
TEST (Homework5, ControllerInterface)
Function Documentation
TEST (Homework5 , ModelDefault)
Definition at line 8 of file test_homework5.cpp.
References homework5::DocumentModel::getPrimitives(), homework5::OK, homework5::DocumentModel::removeAll(), and homework5::DocumentModel::removeLastAdded().
TEST (Homework5 , ModelDataManipulation)
Definition at line 18 of file test_homework5.cpp.
References homework5::DocumentModel::addPrimitive(), homework5::DocumentModel::getPrimitives(), homework5::Line, homework5::OK, homework5::Point, homework5::DocumentModel::removeAll(), and homework5::DocumentModel::removeLastAdded().
TEST (Homework5 , ModelFileStub)
Definition at line 40 of file test_homework5.cpp.
References homework5::DocumentModel::exportToFile(), homework5::DocumentModel::importFromFile(), and homework5::OK.
TEST (Homework5 , ViewDefault)
Definition at line 51 of file test_homework5.cpp.
References homework5::NOT_INITIALIZED, and homework5::ViewCLI::start().
TEST (Homework5 , ControllerInterface)
Definition at line 57 of file test_homework5.cpp.
References homework5::Controller::addLine(), homework5::Controller::addPoint(), homework5::Controller::createDoc(), homework5::Controller::exportDoc(), homework5::Controller::importDoc(), homework5::OK, and homework5::Controller::removeLastAdded().