Tasks: /home/travis/build/gvenewour/miscellaneous/homeworks/homework3/test/test_homework3.cpp File Reference
test_homework3.cpp File Reference
#include "gtest/gtest.h"
#include <map>
#include "common.h"
#include "linear_allocator.h"
#include "custom_list.h"
Typedefs
using CustomMap = std::map< Key, Val, std::less<>, homework3::LinearStatefulAllocator< std::pair< const Key, Val >, maxCount > >
Functions
INITIALIZE_EASYLOGGINGPP TEST (Homework3, CustomAllocator_MapDefault)
TEST (Homework3, CustomAllocator_MapCopyCtor)
TEST (Homework3, CustomAllocator_MapMoveCtor)
TEST (Homework3, CustomAllocator_MapCopyAssignment)
TEST (Homework3, CustomAllocator_MapMoveAssignment)
TEST (Homework3, CustomAllocator_CustomListDefault)
Typedef Documentation
using CustomMap = std::map<Key, Val, std::less<>, homework3::LinearStatefulAllocator<std::pair<const Key, Val>, maxCount> >
Definition at line 11 of file test_homework3.cpp.
Function Documentation
INITIALIZE_EASYLOGGINGPP TEST (Homework3 , CustomAllocator_MapDefault)
Definition at line 15 of file test_homework3.cpp.
References homework3::factorial(), and homework3::maxCount.
TEST (Homework3 , CustomAllocator_MapCopyCtor)
Definition at line 25 of file test_homework3.cpp.
References homework3::factorial(), and homework3::maxCount.
TEST (Homework3 , CustomAllocator_MapMoveCtor)
Definition at line 47 of file test_homework3.cpp.
References homework3::factorial(), and homework3::maxCount.
TEST (Homework3 , CustomAllocator_MapCopyAssignment)
Definition at line 61 of file test_homework3.cpp.
References homework3::factorial(), and homework3::maxCount.
TEST (Homework3 , CustomAllocator_MapMoveAssignment)
Definition at line 87 of file test_homework3.cpp.
References homework3::factorial(), and homework3::maxCount.
TEST (Homework3 , CustomAllocator_CustomListDefault)
Definition at line 106 of file test_homework3.cpp.
References homework3::CustomList< T, A >::insert(), and homework3::maxCount.